basePath: /api/v1
definitions:
  models.Book:
    properties:
      author:
        type: string
      id:
        type: integer
      releasedYear:
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
  description: Swagger API for Golang Project Blueprint.
  termsOfService: http://swagger.io/terms/
  title: Swagger API
  version: "1.0"
paths:
  /book/:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Book'
            type: array
      summary: Get all books
    post:
      parameters:
      - description: Add book
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/models.Book'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
      summary: Add book
    put:
      parameters:
      - description: Update book
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/models.Book'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
      summary: Update book
  /book/{id}:
    delete:
      parameters:
      - description: Book Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete book
    get:
      parameters:
      - description: Book Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
      summary: Get book
swagger: "2.0"
